# Site settings
title: My Diary
logo: "/assets/images/myicon.jpeg"
email: 
description: >-
  渡航の記録
url: "https://ShunsukeOU.github.io"
baseurl: "/blog-Nepal"
github_username: ShunsukeOU
minimal_mistakes_skin: sunrise
search: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    guess_lang: true

remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Tokyo

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Shunsuke"
  avatar : "/assets/images/myicon.jpeg"
  bio    : "2025.08-09、ネパールのカトマンズに渡航。渡航先での学びや日常を記録します。"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ShunsukeOU"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ShunsukeOU"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/